CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(150) NOT NULL,
    building VARCHAR(50) NOT NULL,
    apartment VARCHAR(50),
    postal_code VARCHAR(20)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(16),
    address_id BIGINT,
    father_id BIGINT,
    mother_id BIGINT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    active_email VARCHAR(255)
        GENERATED ALWAYS AS (CASE WHEN is_deleted = FALSE THEN email ELSE NULL END),
    active_phone VARCHAR(16)
        GENERATED ALWAYS AS (CASE WHEN is_deleted = FALSE THEN phone_number ELSE NULL END),
    CONSTRAINT fk_users_address FOREIGN KEY (address_id) REFERENCES addresses(id),
    CONSTRAINT fk_users_father FOREIGN KEY (father_id) REFERENCES users(id),
    CONSTRAINT fk_users_mother FOREIGN KEY (mother_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX ux_users_active_email ON users(active_email);
CREATE UNIQUE INDEX ux_users_active_phone ON users(active_phone);
CREATE INDEX ix_users_father ON users(father_id);
CREATE INDEX ix_users_mother ON users(mother_id);
